### ISSUE TITLE
CORS Error: Failed to load resource - 403 (Invalid origin)

### ISSUE THREAD

**Issue by axsddlr** [jarvis2f/telegram-files#2]
I encountered a CORS error while trying to access the endpoint :6543/api/telegram/create. The server responded with a status code of 403, indicating that the origin is not allowed.

**Error Message**:

```
:6543/api/telegram/create:1 Failed to load resource: the server responded with a status of 403 (CORS Rejected - Invalid origin)
```
**Steps to Reproduce**:

1. Open the web application at http://192.xxx.xxx.xxx:6543/.
2. Attempt to create a telegram via the endpoint :6543/api/telegram/create.
3. Observe the error in the DevTools Console.

**Expected Behavior**: The request should be successfully processed by the server without any CORS issues.

**Actual Behavior**: The request is rejected by the server with a 403 status code due to CORS policy.

**Comment by jarvis2f** [comment]
I didn’t encounter such an issue during my usage because both the web service and API service are accessed using the same address and port, which shouldn’t trigger a CORS error. However, others have raised this issue, indicating that there might indeed be a problem. So, I’d like to know the following:

1. Are you deploying directly using Docker?
2. Is the web page address you’re accessing in the browser consistent with the API request address observed in the console?
3. Could you please provide the Nginx logs? They should be located in the container at: `/var/log/nginx`.

Thanks.

**Comment by tediorelee** [comment]
Same issue here: running `docker-compose` using Unraid

![image](https://github.com/user-attachments/assets/da794cb7-fe5c-4c70-944c-c9688e16a3cb)

Page blank after click create account, I see both API and the url I'm visiting is the same which is `http://192.168.2.167:6543/`

![image](https://github.com/user-attachments/assets/f3e83cd6-88b7-47b4-90bc-6f8582bec5c1)

Nginx `error.log`, `192.168.2.7` is the PC client I'm using to access the webui of `telegram-files`

![image](https://github.com/user-attachments/assets/d4b929d8-c1f1-497e-9393-85d36a20ef96)

Container console `env` output

![image](https://github.com/user-attachments/assets/6dd25605-2df6-4be7-888d-a40c1ce11b8d)

**Comment by axsddlr** [comment]
> I didn’t encounter such an issue during my usage because both the web service and API service are accessed using the same address and port, which shouldn’t trigger a CORS error. However, others have raised this issue, indicating that there might indeed be a problem. So, I’d like to know the following:
> 
> 1. Are you deploying directly using Docker?
> 2. Is the web page address you’re accessing in the browser consistent with the API request address observed in the console?
> 3. Could you please provide the Nginx logs? They should be located in the container at: `/var/log/nginx`.
> 4. The output content after running the 'env' command inside the container
> 
> Thanks.

1. using portainer. shouldnt cause any issue.
2. yes
3. error.log is empty and access.log just shows api health curl outputs `127.0.0.1 - - [29/Dec/2024:16:59:15 +0000] "GET /api/health HTTP/1.1" 200 76 "-" "curl/7.88.1"`
4. 

```Downloading TDLib...
Using TDLib from /app/tdlib/libs/linux_x64
                        -------------
__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__
                          Runtime Edition
        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.
                Start and Daemonize any application:
                $ pm2 start app.js
                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4
                Monitor in production:
                $ pm2 monitor
                Make pm2 auto-boot at server restart:
                $ pm2 startup
                To go further checkout:
                http://pm2.io/
                        -------------
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2024-12-28T23:51:45: PM2 log: Launching in no daemon mode
2024-12-28T23:51:45: PM2 log: [PM2][WARN] Applications telegram-files-web not running, starting...
2024-12-28T23:51:45: PM2 log: App [telegram-files-web:0] starting in -cluster mode-
2024-12-28T23:51:45: PM2 log: App [telegram-files-web:0] online
2024-12-28T23:51:45: PM2 log: [PM2] App [telegram-files-web] launched (1 instances)
Setting telegram.files log level to INFO
2024-12-28T23:51:45: PM2 log: ┌────┬───────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                  │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼───────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ telegram-files-web    │ default     │ 0.1.5   │ cluster │ 58       │ 0s     │ 0    │ online    │ 0%       │ 50.6mb   │ root     │ disabled │
└────┴───────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
2024-12-28T23:51:45: PM2 log: [--no-daemon] Continue to stream logs
2024-12-28T23:51:45: PM2 log: [--no-daemon] Exit on target PM2 exit pid=26
23:51:46 0|telegram-files-web  |    ▲ Next.js 15.0.3
23:51:46 0|telegram-files-web  |    - Local:        http://localhost:3000
23:51:46 0|telegram-files-web  |    - Network:      http://0.0.0.0:3000
23:51:46 0|telegram-files-web  |  ✓ Starting...
23:51:46 0|telegram-files-web  |  ✓ Ready in 424ms
[2024-12-28 23:51:46] [INFO] Database initialized 
[2024-12-28 23:51:46] [INFO] API server started on port 8080 
[2024-12-28 23:51:46] [INFO] Successfully deployed 0 telegram verticles 
[2024-12-28 23:51:46] [INFO] Auto download verticle started!
|History scan interval: 120000 ms
|Download interval: 10000 ms
|Download limit: 5 per telegram account!
|Auto chats: 0
 
[2024-12-28 23:51:46] [INFO] ?Start success ```

**Comment by jarvis2f** [comment]
@tediorelee 
`APP_ENV=dev`is incorrect, the correct one should be `APP_ENV=prod`.
The environment variable settings in `docker-compose.yaml` file can be directly specified as follows:

```yaml
    environment:
      APP_ENV: "prod"
```

@axsddlr I think your problem is also caused by this reason. You can check the output of the `env` command in the container.

**Comment by axsddlr** [comment]
> @tediorelee `APP_ENV=dev`is incorrect, the correct one should be `APP_ENV=prod`. The environment variable settings in `docker-compose.yaml` file can be directly specified as follows:
> 
> ```yaml
>     environment:
>       APP_ENV: "prod"
> ```
> 
> @axsddlr I think your problem is also caused by this reason. You can check the output of the `env` command in the container.

that did the trick. I would suggest updating your env.example to prod

https://github.com/jarvis2f/telegram-files/blob/d83500cf1b0051e2e1082adf2c01d96b011a1120/.env.example#L1C1-L11C21

**Comment by tediorelee** [comment]
@jarvis2f That solved my issue too, thanks for the update, I just copied `env.example` and changed hash and id
